name: Builds

on:
  push:
    branches: [master]



env:
  flutter_version: "1.22.5"
  java_version: "8.x"
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Upgrade dependencies
        run: flutter pub upgrade
      - name: Install dependencies
        run: flutter pub get
      - name: Checkout to Beta channel
        run: flutter channel beta
      - name: Upgrade dependencies
        run: flutter upgrade --force
      - name: Enable web configurations
        run: flutter config --enable-web
      - name: Run Clean to reduce app sizes
        run: flutter clean
      - name: Build debug apk
        run: flutter build apk --split-per-abi --no-tree-shake-icons  --debug  --no-sound-null-safety
      - name: Build debug app-bundle
        run: flutter build appbundle  --debug  --no-sound-null-safety

      #- name: Enable Web
       # run: flutter create ./
      - name: Build Web
        run: flutter build web --no-sound-null-safety
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.

      - name: Deploy debug apk 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          branch: master # The branch the action should deploy to.
          repository-name: ospic/deploys
          target-folder: mobile/apks/debug
          folder: build/app/outputs/apk/debug # The folder the action should deploy.


      - name: Deploy debug appbundle 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          branch: master # The branch the action should deploy to.
          repository-name: ospic/deploys
          target-folder: mobile/appbundle/debug
          folder: build/app/outputs/bundle/debug # The folder the action should deploy.


      - name: Clean
        run: flutter clean
      - name: Build release apk
        run: flutter build apk  --split-per-abi --no-tree-shake-icons  --release --no-sound-null-safety
      - name: Build release app-bundle
        run: flutter build appbundle   --release --no-sound-null-safety

      - name: Deploy release apk 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          branch: master # The branch the action should deploy to.
          repository-name: ospic/deploys
          target-folder: mobile/apks/release
          folder: build/app/outputs/apk/release # The folder the action should deploy.

      - name: Deploy release appbundle 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          branch: master # The branch the action should deploy to.
          repository-name: ospic/deploys
          target-folder: mobile/appbundle/release
          folder: build/app/outputs/bundle/release # The folder the action should deploy.
