name: Flutter Builds

on:
  push:
    branches: [master]



env:
  flutter_version: "1.22.5"
  java_version: "8.x"
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Upgrade dependencies
        run: flutter pub upgrade
      - name: Install dependencies
        run: flutter pub get
      - name: Checkout to Beta channel
        run: flutter channel beta
      - name: Upgrade dependencies
        run: flutter upgrade --force
      - name: Enable web configurations
        run: flutter config --enable-web
      - name: Run Clean to reduce app sizes
        run: flutter clean
      - name: Build apk
        run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
      - name: Build app-bundle
        run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64
      - name: Enable Web
        run: flutter create ./
      - name: Build Web
        run: flutter build web
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/web # The folder the action should deploy.

