name: Projects

on:
  push:
    branches: [master]
  pull_request:
    branches: [opened, labeled, master]
  issues:
    types: [opened, labeled]



env:
  flutter_version: "1.22.5"
  java_version: "8.x"
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:

  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Projects
    steps:
      - name: Assign NEW issues and NEW pull requests to CHILD project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened'
        with:
          project: "https://github.com/ospic/mobile/projects/1"

      - name: Assign issues and pull requests with `enhancement` label to CHILD project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.labels.*.name, 'enhancement') ||
          contains(github.event.pull_request.labels.*.name, 'enhancement')
        with:
          project: "https://github.com/ospic/mobile/projects/1"
          column_name: "To do"
      - name: Assign NEW issues and NEW pull requests to HEADER project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened'
        with:
          project: "https://github.com/orgs/ospic/projects/1"

      - name: Assign issues and pull requests with `enhancement` label to HEADER project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.labels.*.name, 'enhancement') ||
          contains(github.event.pull_request.labels.*.name, 'enhancement')
        with:
          project: "https://github.com/orgs/ospic/projects/1"
          column_name: "To do"